In [2]:
# pip install numpy
# conda install numpy
import numpy as np

In [3]:
print(type([1,2,3]))
print(type((1,2,3)))
print(type(np.array([1,2,3])))
print(type(np.array((1,2,3))))

<class 'list'>
<class 'tuple'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [14]:
np.zeros(5) # 1 solo numero para un arreglo
np.zeros([5,5]) # 1 lista o tupla para una matriz de n dimensiones
np.zeros((5,5)) 
np.zeros([1000,200]) 
np.zeros((2,3,4,5))

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

In [16]:
np.ones(7)
np.ones((1,2,3,4))

array([[[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]]])

In [19]:
np.eye(10) # Identidad

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [20]:
np.arange(5) # 1 parametros, # de elementos

array([0, 1, 2, 3, 4])

In [22]:
np.arange(4,21) # [4, 20[

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [23]:
np.arange(-12,1) # [-12, 1[

array([-12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0])

In [24]:
np.arange(0,20,2) # Del [-0, 20[ en intervalos de 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [26]:
np.arange(0,2.1,0.1) 

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. ])

In [31]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [32]:
np.zeros(20).reshape(2,5,2).reshape(20)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [33]:
len(np.ones(12))

12

In [35]:
len(np.ones(12).reshape(4,3))

4

In [36]:
np.ones(12).reshape(4,3) # Cambiamos las dimensiones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [37]:
np.ones(12).reshape(4,3).shape # El numero de dimensiones 

(4, 3)

In [42]:
arreglo = np.ones(12).reshape(4,3)

In [43]:
len(arreglo[0])

3

In [44]:
len(arreglo)

4

In [45]:
arreglo.shape

(4, 3)

In [50]:
np.arange(12).reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [54]:
np.arange(12).reshape(4,3)[1][2]

5

In [53]:
np.arange(12).reshape(4,3)[1,2]

5

In [56]:
np.array([1,7,12,16]).reshape(2,2)

array([[ 1,  7],
       [12, 16]])

In [57]:
a = np.array([10,10,10])
b = np.array([5,5,5])

In [60]:
# Suma
a + b

array([15, 15, 15])

In [61]:
# Resta
a - b

array([5, 5, 5])

In [63]:
# Suma
a + 7

array([17, 17, 17])

In [64]:
# Resta
a - 8

array([2, 2, 2])

In [65]:
# Multiplicacion
a * b

array([50, 50, 50])

In [66]:
# Multiplicacion
a * 3

array([30, 30, 30])

In [67]:
# Division
a / b

array([2., 2., 2.])

In [69]:
# Division
a / 2

array([5., 5., 5.])

In [73]:
# Modulo
a % b

array([0, 0, 0])

In [74]:
# Modulo
a % 3

array([1, 1, 1])

In [75]:
muestra = np.arange(20).reshape(5,2,2)

In [76]:
muestra

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19]]])

In [77]:
respuesta_glucosa = muestra > 5

In [79]:
respuesta_glucosa

array([[[False, False],
        [False, False]],

       [[False, False],
        [ True,  True]],

       [[ True,  True],
        [ True,  True]],

       [[ True,  True],
        [ True,  True]],

       [[ True,  True],
        [ True,  True]]])

In [80]:
muestra[respuesta_glucosa]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [93]:
# Mayores a 5 glucosa y Menores a 14 y que sean pares
mayores_cinco = muestra > 5
menores_catorce = muestra < 14
pares = muestra % 2 == 0
respuesta = mayores_cinco & menores_catorce & pares

In [84]:
muestra[respuesta]

array([ 6,  8, 10, 12])

In [88]:
muestra[(muestra > 5) & (muestra < 14) & (muestra % 2 == 0)]


array([ 6,  8, 10, 12])

In [5]:
A = np.arange(4).reshape((2,2))
A

array([[0, 1],
       [2, 3]])

In [6]:
B = np.arange(4, 8).reshape((2,2))
B


array([[4, 5],
       [6, 7]])

In [7]:
A.dot(B)

array([[ 6,  7],
       [26, 31]])

In [8]:
B.dot(A)

array([[10, 19],
       [14, 27]])

In [9]:
np.dot(A,B)

array([[ 6,  7],
       [26, 31]])

In [10]:
np.dot(B,A)

array([[10, 19],
       [14, 27]])

In [12]:
arreglo_doce = np.arange(12)
arreglo_doce

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [13]:
arreglo_doce.sum()

66

In [15]:
arreglo_doce.min()

0

In [14]:
arreglo_doce.max()

11

In [16]:
arreglo_doce[5:].sum()

56

In [17]:
arreglo_doce.reshape(3,2,2)

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [20]:
arreglo_doce.reshape(3,2,2).sum()

66

In [21]:
arreglo_doce.reshape(3,2,2).sum(axis = 0)

array([[12, 15],
       [18, 21]])

In [22]:
arreglo_doce.reshape(3,2,2).sum(axis = 1)

array([[ 2,  4],
       [10, 12],
       [18, 20]])

In [24]:
arreglo_doce.reshape(3,2,2)

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [25]:
arreglo_doce.reshape(3,2,2).sum(axis = 2)

array([[ 1,  5],
       [ 9, 13],
       [17, 21]])